### ISSUE TITLE
Discoverable

### ISSUE THREAD

**Issue by pergolafabio** [RogerSelwyn/mqtt_discoverystream_ha#31]
Hi,

I'm using this integration to expose lights/switches  to Openhab...

```
mqtt_discoverystream_alt:
  base_topic: openhab
  publish_attributes: true
  publish_timestamps: false
  publish_discovery: true
  include:
    domains:
      - light
      - switch
```
In MQTT explorer, i see the entities being created on the base topic "openhab"

![image](https://github.com/user-attachments/assets/9411a9ce-0994-4f3a-9bdd-305646a5326f)

So far so good, but if i install OpenHab, it cant discover the entities? only the ones with hmd/homeassistant?
What am i missing here? How can i make the discoverable?

![image](https://github.com/user-attachments/assets/2f6fd5e4-b711-4340-a638-a0a4a9fb304a)
thnx

**Comment by RogerSelwyn** [comment]
I have no idea how OpenHab works, so no idea what it is doing. That said, the way you have mqttds configured the discovery topics are within the openhab topic. 


The discovery messages are key, and are separate from the status messages. Discovery messages tell home Assistant where to find the statuses messages. 

Normally with home Assistant they would be within the homeassistant topic when you have something like zigbee2mqtt since the entities detailed there would be new to the home Assistant instance. 

I would imagine openhab will be looking in the homeassistant topic. You can configure where they are put using the ‘discovery_topic’ configuration setting. But if you set that to ‘homeassistant’ you will find that all your entities will get recreated in your home Assistant instance (assuming you have it setup to defaults) because it thinks they are new, which is why the Integration doesn’t output there as standard (it puts them under base_topic). 

So you need to also be able to tell openhab where to find them, which I can’t help you with.

**Comment by pergolafabio** [comment]
Ah ok , in Openhab it'd an "HA binding" , do probably follow the defaults... I think I need to create every mqtt entity manual in HA ... A lot of copy/paste then :-)

**Comment by pergolafabio** [comment]
hey @RogerSelwyn , creating custom mqtt entities are working  , 1 question however, if i restart Openhab, openhab things the mqtt is offline, as soon as i turn on/off light manually, the light comes online in Openhab
Probably when i restart Openhab, its doesnt know the availability (online vs offline) topic?

![image](https://github.com/user-attachments/assets/681f18d3-b609-4c82-aef8-0038417f65eb)


is it somehow possible to retain that message/topic?
![image](https://github.com/user-attachments/assets/5b840aab-becc-49d7-96a7-262231c5d31b)


```
UID: mqtt:topic:4195962e3b
label: Bureau
thingTypeUID: mqtt:topic
configuration:
  payloadNotAvailable: offline
  availabilityTopic: openhab/light/bureau/availability
  payloadAvailable: online
bridgeUID: mqtt:broker:aff82bad06
channels:
  - id: Bureau
    channelTypeUID: mqtt:switch
    label: On/Off Switch
    configuration:
      commandTopic: openhab/light/bureau/set_light
      stateTopic: openhab/light/bureau/state
      transformationPattern: JSONPATH:$.state
      off: '{ "state": "OFF" }'
      on: '{ "state": "ON" }'
```
