### ISSUE TITLE
value_template: "false"

### ISSUE THREAD

**Issue by pergolafabio** [RogerSelwyn/mqtt_discoverystream_ha#32]
Hey, i have some switches without a value template, its more like a momentary switch, when i turn it on, it goes back to off state...
Seems those switches are not visible in mqtt explorer? they are not published at all , is there another way to make them visible?

thnx in advance

```
   openhab_volume_zone2:
     value_template: "false"
     turn_on:
       - service: script.volume_down_zone2
     turn_off:
       - service: script.volume_up_zone2
```

**Comment by pergolafabio** [comment]
yes, they are
as soon i delete this line below, they are visible in mqtt

`value_template: "false"`

but i want to have the switches off at all time :-)

**Comment by RogerSelwyn** [comment]
I'll try to take a look, won't be until Monday.

**Comment by pergolafabio** [comment]
perfect, thnx in advance!

**Comment by RogerSelwyn** [comment]
Anything in the logs. A very quick code look didn't reveal any restriction.

**Comment by pergolafabio** [comment]
i'm now creating somekind of workaround, to set only the "state" to off again, when i turn it on, not sure if thats going to work...

```
   openhab_volume_zone2:
     turn_on:
       - service: script.volume_up_zone2
       - delay: '00:00:2' 
       - service: python_script.set_statev3
         data_template:
           entity_id: switch.openhab_volume_zone2
           state: 'off'
```

**Comment by pergolafabio** [comment]
whats also strange, if i work without the value template like below
It all works, if i restart HA , then sending topics to the switch dont do anything
Untill, i fist manually turn the entity on or off in HA itself, if i then send topics to mqtt, then they start working

is there a way to work around this?

```
   openhab_volume_zone2:
     turn_on:
       - service: script.volume_up_zone2
     turn_off:
       - service: script.volume_down_zone2
```

**Comment by pergolafabio** [comment]
Is it needed that switches need a value template? So they send it to mqtt when you restart HA?

**Comment by RogerSelwyn** [comment]
> whats also strange, if i work without the value template like below It all works, if i restart HA , then sending topics to the switch dont do anything Untill, i fist manually turn the entity on or off in HA itself, if i then send topics to mqtt, then they start working
> 
> is there a way to work around this?
> 
> ```
>    openhab_volume_zone2:
>      turn_on:
>        - service: script.volume_up_zone2
>      turn_off:
>        - service: script.volume_down_zone2
> ```

Without you giving exact details on what you are doing add how long you are waiting it is probably impossible for me to guess why things aren’t working as expected. As I’ve said before I don’t use openhab, and this is designed for an ha mqtt client at either end. So I’m not going to start guessing what you are doing or sending from openhab. If you can test with ha at either end I’ll figured out why it isn’t working

**Comment by RogerSelwyn** [comment]
> Is it needed that switches need a value template? So they send it to mqtt when you restart HA?

All discovery and state for relevant entities should be sent at ha startup. It tries to wait until ha has completely started so that all entities are available before sending. It should then resend on a scheduled basis (I forget what the gap is). It will also send when you run the service out it receives a birth message from the remote ha instance. 

I believe this is described in the docs. 

I will check if there is something different for when there is a value template, but I don’t believe there is. It maybe something is ha is doing.

**Comment by pergolafabio** [comment]
ok, i make it more clear... its not related to openhab, i have some lights like below with value template

```
    slaapkamer3:
      friendly_name: "Alessio"
      value_template: "{{ state_attr('sensor.dobiss', '4203') == '01' }}"
      turn_on:
        - service: shell_command.dobiss
          data_template:
            module: 42
            id: 3
            power: 01
      turn_off:
        - service: shell_command.dobiss
          data_template:
            module: 42
            id: 3
            power: 00
```

When i restart HA, to make sure, i also do this service:
`action: mqtt_discoverystream_alt.publish_discovery_state`

when i then send this command:
`mosquitto_pub -h localhost -p 1883 -t "openhab/light/slaapkamer3/set_light" -m '{ "state": "ON" }'`

the light DOESNT turn on!! thats my issue
When i turn first the light ON and the OFF again in HA, then resending this command:

`mosquitto_pub -h localhost -p 1883 -t "openhab/light/slaapkamer3/set_light" -m '{ "state": "ON" }'`

Now my light turns on!! 

next test
The light is turned ON, before i restart HA
when HA is restarted, i can now turn my light OFF with this command:

`mosquitto_pub -h localhost -p 1883 -t "openhab/light/slaapkamer3/set_light" -m '{ "state": "OFF" }'`

**Comment by RogerSelwyn** [comment]
Because you didn't give your template entities a unique ID, they don't appear in the entity registry (which is what is searched when you run the service), so they don't get sent out as part of the discovery/state publish when you run the service.

I suspect they don't get published when you turn them 'on', because the state never changes because you have set it to 'off'.

It's always better to give template entities a unique id, because then they are more manageable through the UI and makes them more discoverable in code.

  ```yaml
openhab_volume_zone2:
    unique_id: openhab_volume_zone2
    value_template: "false"
     turn_on:
       - service: script.volume_down_zone2
     turn_off:
       - service: script.volume_up_zone2
```
